name: Publish Builds

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci
      - run: npm run electron:build -p always
        env:
          GH_TOKEN: ${{ secrets.github_token }}
